version: "3.1"

volumes:
  dask-shared:
    name: "dask-shared"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\Dev\_Docker\dask-docker\dask-shared-volume

services:
  dask-scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
      args:
        release: "2021.12.0"
    hostname: dask-scheduler
    container_name: dask-scheduler
    ports:
    - "8786:8786"
    - "8787:8787"
    command: ["dask-scheduler"]
    volumes:
    - dask-shared:/opt/dask-shared

  dask-worker:
    build:
      context: ./base
      dockerfile: Dockerfile
      args:
        python: "3.8"
        release: "2021.12.0"
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
    depends_on:
    - dask-scheduler
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: 2000m
          memory: 4G

  notebook:
    image: daskdev/dask-notebook:latest
    hostname: notebook
    container_name: dask-notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://dask-scheduler:8786"
    command: "start.sh jupyter notebook --NotebookApp.token=''"
    volumes:
    - dask-shared:/home/jovyan/work
